import React, { Component } from 'react';

class About extends Component {
  render() {
    return(
      <div>
        <h2>About</h2>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>
        <p>Hexagon try-hard pabst, tbh authentic hot chicken plaid crucifix lomo knausgaard. Franzen paleo normcore cred, pop-up shabby chic air plant ethical tumeric direct trade. Edison bulb drinking vinegar shoreditch vice poke 90's kombucha pug unicorn next level air plant mumblecore. Echo park actually gluten-free schlitz hammock. Mixtape austin master cleanse succulents, authentic thundercats gentrify food truck whatever craft beer tbh roof party. Gentrify taxidermy humblebrag lyft crucifix tousled, hella twee chambray man bun ugh tote bag.</p>        
      </div>
    )
  }
}

export default About;